name: Deploy to IONOS using SFTP

on:
  push:
    branches:
      - Master  # Rama que activa el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar la clave SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H home496960781.1and1-data.host >> ~/.ssh/known_hosts

      # Paso 3: Subir archivos usando SFTP
      - name: Clean remote folder
        run: |
          sftp acc1831091850@home496960781.1and1-data.host <<EOF
          rm -r /108LMSGIProyectoLMSGI/*
          bye
          EOF
      
      - name: Deploy using SFTP
        run: |
          sftp acc1831091850@home496960781.1and1-data.host <<EOF
          put -r ./ /108LMSGIProyectoLMSGI/
          bye
          EOF



